export const distritos = [
    "Distrito de San Felipe Jalapa de Díaz",
    "Distrito de San Juan Bautista Tuxtepec",
    "Distrito de Loma Bonita",
    "Distrito de Teotitlán de Flores Magón",
    "Distrito de Asunción Nochixtlán",
    "Distrito de Heroica Ciudad de Huajuapan de León",
    "Distrito de Putla Villa de Guerrero",
    "Distrito de Heroica Ciudad de Tlaxiaco",
    "Distrito de Ixtlán de Juárez",
    "Distrito de San Pedro y San Pablo Ayutla",
    "Distrito de Matías Romero",
    "Distrito de Santa Lucia del Camino",
    "Distrito de Oaxaca de Juárez",
    "Distrito de Villa de Etla",
    "Distrito de Santa Cruz Xoxocotlán",
    "Distrito de Zimatlán de Álvarez",
    "Distrito de Tlacolula de Matamoros",
    "Distrito de Santo Domingo Tehuantepec",
    "Distrito de Ciudad Ixtepec",
    "Distrito de Juchitán de Zaragoza",
    "Distrito de Ocotlán de Morelos",
    "Distrito de Santiago Pinotepa Nacional",
    "Distrito de Puerto Escondido",
    "Distrito de Miahuatlán de Porfirio Díaz"
];
