export const marcasComerciales = [
    'Toyota',
    'Volkswagen',
    'Ford',
    'Chevrolet',
    'Honda',
    'Nissan',
    'Hyundai',
    'Kia',
    'BMW',
    'Mercedes-Benz',
    'Audi',
    'Renault',
    'Peugeot',
    'Fiat',
    'Volvo',
  ];